/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include "nanopb\pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(1024) SPT_Data_data_t;
/* Size: 16 + Payload (Max 1040) */
typedef struct _SPT_Data {
    pb_byte_t ulid[16];
    SPT_Data_data_t data;
} SPT_Data;

typedef PB_BYTES_ARRAY_T(1024) SPT_Task_payload_t;
/* Size: 32 + Payload (Max 1056) */
typedef struct _SPT_Task {
    uint16_t flags;
    pb_byte_t ulid[16];
    /* RPC */
    uint16_t module;
    uint16_t method;
    uint16_t status;
    /* If size > payload, expect more tasks with same id */
    uint64_t size;
    SPT_Task_payload_t payload;
} SPT_Task;

typedef struct _SPT_Payload {
    pb_size_t which_payload;
    union _SPT_Payload_payload {
        SPT_Task task;
        SPT_Data data;
    } payload;
} SPT_Payload;

/* Size: 34 bytes */
typedef struct _SPT_Route {
    uint8_t priority;
    uint8_t hopcount;
    pb_byte_t source[16];
    pb_byte_t destination[16];
} SPT_Route;

/* Size: 1 + 34 + 4 (39) + Payload = 1166 Max bytes */
typedef struct _SPT_Header {
    uint8_t version;
    bool has_route;
    SPT_Route route;
    /* Validate excludes route hopcount */
    uint32_t crc;
    /* One message may contain multiple payloads, upto 1127 bytes total */
    pb_callback_t payload;
} SPT_Header;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SPT_Data_init_default                    {{0}, {0, {0}}}
#define SPT_Task_init_default                    {0, {0}, 0, 0, 0, 0, {0, {0}}}
#define SPT_Payload_init_default                 {0, {SPT_Task_init_default}}
#define SPT_Route_init_default                   {0, 0, {0}, {0}}
#define SPT_Header_init_default                  {0, false, SPT_Route_init_default, 0, {{NULL}, NULL}}
#define SPT_Data_init_zero                       {{0}, {0, {0}}}
#define SPT_Task_init_zero                       {0, {0}, 0, 0, 0, 0, {0, {0}}}
#define SPT_Payload_init_zero                    {0, {SPT_Task_init_zero}}
#define SPT_Route_init_zero                      {0, 0, {0}, {0}}
#define SPT_Header_init_zero                     {0, false, SPT_Route_init_zero, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define SPT_Data_ulid_tag                        1
#define SPT_Data_data_tag                        2
#define SPT_Task_flags_tag                       1
#define SPT_Task_ulid_tag                        2
#define SPT_Task_module_tag                      3
#define SPT_Task_method_tag                      4
#define SPT_Task_status_tag                      5
#define SPT_Task_size_tag                        6
#define SPT_Task_payload_tag                     7
#define SPT_Payload_task_tag                     1
#define SPT_Payload_data_tag                     2
#define SPT_Route_priority_tag                   1
#define SPT_Route_hopcount_tag                   2
#define SPT_Route_source_tag                     3
#define SPT_Route_destination_tag                4
#define SPT_Header_version_tag                   1
#define SPT_Header_route_tag                     2
#define SPT_Header_crc_tag                       3
#define SPT_Header_payload_tag                   4

/* Struct field encoding specification for nanopb */
#define SPT_Data_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, ulid,              1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define SPT_Data_CALLBACK NULL
#define SPT_Data_DEFAULT NULL

#define SPT_Task_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   flags,             1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, ulid,              2) \
X(a, STATIC,   SINGULAR, UINT32,   module,            3) \
X(a, STATIC,   SINGULAR, UINT32,   method,            4) \
X(a, STATIC,   SINGULAR, UINT32,   status,            5) \
X(a, STATIC,   SINGULAR, UINT64,   size,              6) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           7)
#define SPT_Task_CALLBACK NULL
#define SPT_Task_DEFAULT NULL

#define SPT_Payload_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,task,payload.task),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,data,payload.data),   2)
#define SPT_Payload_CALLBACK NULL
#define SPT_Payload_DEFAULT NULL
#define SPT_Payload_payload_task_MSGTYPE SPT_Task
#define SPT_Payload_payload_data_MSGTYPE SPT_Data

#define SPT_Route_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   priority,          1) \
X(a, STATIC,   SINGULAR, UINT32,   hopcount,          2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, source,            3) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, destination,       4)
#define SPT_Route_CALLBACK NULL
#define SPT_Route_DEFAULT NULL

#define SPT_Header_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  route,             2) \
X(a, STATIC,   SINGULAR, UINT32,   crc,               3) \
X(a, CALLBACK, REPEATED, MESSAGE,  payload,           4)
#define SPT_Header_CALLBACK pb_default_field_callback
#define SPT_Header_DEFAULT NULL
#define SPT_Header_route_MSGTYPE SPT_Route
#define SPT_Header_payload_MSGTYPE SPT_Payload

extern const pb_msgdesc_t SPT_Data_msg;
extern const pb_msgdesc_t SPT_Task_msg;
extern const pb_msgdesc_t SPT_Payload_msg;
extern const pb_msgdesc_t SPT_Route_msg;
extern const pb_msgdesc_t SPT_Header_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SPT_Data_fields &SPT_Data_msg
#define SPT_Task_fields &SPT_Task_msg
#define SPT_Payload_fields &SPT_Payload_msg
#define SPT_Route_fields &SPT_Route_msg
#define SPT_Header_fields &SPT_Header_msg

/* Maximum encoded size of messages (where known) */
/* SPT_Header_size depends on runtime parameters */
#define MESSAGE_PB_H_MAX_SIZE                    SPT_Payload_size
#define SPT_Data_size                            1045
#define SPT_Payload_size                         1075
#define SPT_Route_size                           42
#define SPT_Task_size                            1072

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
