/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SPT_Route, SPT_Route, AUTO)


PB_BIND(SPT_Task, SPT_Task, AUTO)


PB_BIND(SPT_Header, SPT_Header, AUTO)



