/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SPT_Data, SPT_Data, 2)


PB_BIND(SPT_Task, SPT_Task, 2)


PB_BIND(SPT_Payload, SPT_Payload, 2)


PB_BIND(SPT_Route, SPT_Route, AUTO)


PB_BIND(SPT_Header, SPT_Header, AUTO)



